tls_server_config:
  <% if_p('prometheus.web.tls_server_config.cert_contents') do |cert_contents| %>
  cert_file: /var/vcap/jobs/prometheus2/config/web_tls_server.crt
  <% end %>

  <% if_p('prometheus.web.tls_server_config.key_contents') do |key_contents| %>
  key_file: /var/vcap/jobs/prometheus2/config/web_tls_server.key
  <% end %>

  <% if_p('prometheus.web.tls_server_config.client_ca_contents') do |client_ca_contents| %>
  client_ca_file: /var/vcap/jobs/prometheus2/config/web_tls_server_client_ca.crt
  <% end %>

  <% if_p('prometheus.web.tls_server_config.client_auth_type') do |client_auth_type| %>
  client_auth_type: <%= client_auth_type %>
  <% end %>

  <% if_p('prometheus.web.tls_server_config.min_version') do |min_version| %>
  min_version: <%= min_version %>
  <% end %>

  <% if_p('prometheus.web.tls_server_config.max_version') do |max_version| %>
  max_version: <%= max_version %>
  <% end %>

  <% if_p('prometheus.web.tls_server_config.cipher_suites') do |cipher_suites| %>
  cipher_suites: <%= cipher_suites.to_json %>
  <% end %>

  <% if_p('prometheus.web.tls_server_config.prefer_server_cipher_suites') do |prefer_server_cipher_suites| %>
  prefer_server_cipher_suites: <%= prefer_server_cipher_suites.to_json %>
  <% end %>

  <% if_p('prometheus.web.tls_server_config.curve_preferences') do |curve_preferences| %>
  curve_preferences: <%= curve_preferences.to_json %>
  <% end %>

http_server_config:
  <% if_p('prometheus.web.http_server_config.http2') do |http2| %>
  http2: <%= http2 %>
  <% end %>

  <% if_p('prometheus.web.http_server_config.headers') do |headers| %>
  headers: <%= headers.to_json %>
  <% end %>
